Update umount_image
In this version, the script hardcodes the directory path to "/mnt/diskimage" and sets the "-f" flag to force the unmount. If the unmount command fails, the script prints an error message and exits with a non-zero status code.

diff --git a/Scripts/umount_image b/Scripts/umount_image
--- a/Scripts/umount_image
+++ b/Scripts/umount_image
@@ -1,28 +1,17 @@
 #!/bin/sh -e
 
-case $# in
-1)
-    ;;
-*)
-    while [ $# -gt 1 ]; do
-	flags="$flags $1"
-	shift
-    done
-    ;;
-esac
-	
-dir="$1"
-# mount | awk -v dir="$dir" '$3 == dir { print $3 }'
-if [ 0`mount | awk -v dir="$dir" '$3 == dir { print $3 }'` != 0"$dir" ]; then
-    printf "\nError: $dir not found in current mount table.  Options are:\n\n"
-    mount | awk ' { print $3 }'
+dir="/mnt/diskimage"
+flags="-f"
+
+if ! umount $flags $dir; then
+    printf "\nError: failed to unmount $dir\n"
+    exit 1
 fi
 
 dev=`mount | awk -v dir="$dir" '$3 == dir { print $1 }'`
 vol=${dev%s*}
 devnum=${vol#/dev/md}
 
-if umount $flags $dir; then
-    mdconfig -d -u $devnum
-fi
+mdconfig -d -u $devnum
+
 
